---
title: "Classroom philosophy"
editor: visual
---

***Everyone is still learning.*** Learning is lifelong, because no one knows everything. A moment's reflection (and a bit of humility) reveals that for each of us, our ignorance far outweighs our knowledge, and no amount of study or effort will tip this balance in the other direction. But this is cause for optimism: regardless of experience, each of us can always find something new to work on and some way to grow. Further, those opportunities are highly particular to each of us. Even if you and I acquire the same skill or fact, as so often happens in a college course with seemingly fixed content, our relationship to that skill or fact is personal and distinct -- so even then it might be said we've learned different things. Our collective goal in the classroom should be to encourage and work with this individuality. We should resist the temptation to compare and not hold to the idea that any one of us has achieved anything more or less than anyone else. We should help each other to find our own learning opportunities through careful listening, constructive questioning, and positive feedback, and we should give back the benefits we receive by sharing our personal discoveries. This way we will keep learning.

***No particular ability or skill defines success in data science.*** Data science involves a combination of computing, statistics and probability, and domain expertise. It also involves the use of technology and the practice of narrative communication and storytelling. You can probably think of one or two other aspects of the discipline to add to the list. Emerging curricula in data science seek to balance core competencies across these or similar areas. (Perhaps this is the present hallmark of the discipline.) Yet, no one person can expect to be an expert in all of these areas, and even core competencies across component areas can look a bit different from person to person among perfectly qualified data scientists. We should all accept that we have strengths and weaknesses and resist the temptation to idealize: that is, to associate a particular constellation -- whether that's our own, the opposite of our own, or another idea idea we have -- of abilities with 'better' data science. If we can know our own balance of skills (and interests), be open to healthy challenges, and focus on what we can do well and how we can improve, that is enough.
