---
title: "Syllabus"
editor: visual
---

***Catalog description:*** Introduction to research skills. Discussion of current research trends, writing literature reviews, etc. Students will be required to present materials reflecting their interests, which will be critically appraised for both content and presentation. Emphasis will be placed on aiding students to acquire a high-level of professionalism. *Prerequisite: PSTAT126.*

## Meetings

Class meetings are held 2pm -- 3:15pm Tuesdays and Thursdays in Ellison 2617.

Section meetings are held Wednesdays:

-   2pm -- 2:50pm in Girvetz 2115;

-   3pm -- 3:50pm in Girvetz 2116;

-   4pm -- 4:50pm in North Hall 1109.

## Course staff

***Instructor**:*

-   *Trevor Ruiz.* Visiting assistant professor and co-instructor for 2021-2022 capstone projects.

***Teaching assistants:***

-   *Erika McPhillips.* MS student and capstone project mentor in 2021-2022.

-   *Joshua Bang.* MS student and capstone project mentor in 2021-2022.

-   *Meghan Elcheikhali.* PhD student and capstone project mentor in 2021-2022.

***Undergraduate learning assistant:***

-   *Yan Lashchev.* BS student and Data Science Fellow at UCSB in 2021-2022.

## Schedule

This schedule is tentative and may be adjusted at the discretion of the instructor.

+------------+---------------+------------------------------------------------------------+--------------------------------------------------------+-------------------------------------+
| Week       | Theme         | Tuesday meeting                                            | Thursday meeting                                       | Section meeting                     |
+============+===============+============================================================+========================================================+=====================================+
| 0          | Introductions | NO CLASS                                                   | Lecture: on research projects in(volving) data science | NO LAB                              |
+------------+---------------+------------------------------------------------------------+--------------------------------------------------------+-------------------------------------+
| 1          | Introductions | Lecture: on data science as a discipline                   | 0.1 Discussion: class data                             | Software and technology overview    |
|            |               |                                                            |                                                        |                                     |
|            | Module 0      |                                                            |                                                        |                                     |
+------------+---------------+------------------------------------------------------------+--------------------------------------------------------+-------------------------------------+
| 2          | Module 0      | 0.2 Lecture: on descriptive analysis                       | 0.3 Discussion: results                                | tidyverse basics                    |
+------------+---------------+------------------------------------------------------------+--------------------------------------------------------+-------------------------------------+
| 3          | Module 1      | 1.1 Discussion                                             | 1.2 Lecture: on regression                             | lm()                                |
+------------+---------------+------------------------------------------------------------+--------------------------------------------------------+-------------------------------------+
| 4          | Module 1      | 1.3 Lecture: on prediction                                 | 1.4 Discussion                                         | modelr and tidymodels               |
+------------+---------------+------------------------------------------------------------+--------------------------------------------------------+-------------------------------------+
| 5          | Module 2      | 2.1 Discussion: biomarker data                             | 2.2 Lecture: on classification                         | glm()                               |
+------------+---------------+------------------------------------------------------------+--------------------------------------------------------+-------------------------------------+
| 6          | Module 2      | 2.3 Lecture: on variable selection and variable importance | 2.4 Discussion: results                                | glmnet and randomForest             |
+------------+---------------+------------------------------------------------------------+--------------------------------------------------------+-------------------------------------+
| 7          | Module 3      | 3.1 Discussion: soil temperature data                      | 3.2 Lecture: on time                                   | curve fitting; ts forecasting       |
+------------+---------------+------------------------------------------------------------+--------------------------------------------------------+-------------------------------------+
| 8          | Module 3      | 3.3 Lecture: on space                                      | 3.4 Discussion: results                                | inverse distance weighting; kriging |
+------------+---------------+------------------------------------------------------------+--------------------------------------------------------+-------------------------------------+
| 9          | Module 4      | 4.1                                                        | NO CLASS                                               | NO LAB                              |
+------------+---------------+------------------------------------------------------------+--------------------------------------------------------+-------------------------------------+
| 10         | Module 4      | 4.2                                                        | 4.3 Discussion: in closing                             | Interviews                          |
+------------+---------------+------------------------------------------------------------+--------------------------------------------------------+-------------------------------------+

## Expectations and assessments

Much of the course is designed around group activity and discussion. Students are therefore expected to:

-   prepare for class meetings by completing any assigned reading or activity;

-   attend class meetings and actively participate;

-   provide meaningful and concrete contributions to group activities;

-   submit assignments in a timely fashion.

Students having any difficulty in meeting these expectations should raise the issue(s) promptly with the instructor.

Qualitative feedback is emphasized over numerical scores. Students are assessed on:

-   attendance, preparation, and participation;

-   quality of submitted work;

-   individual contributions to group assignments;

-   oral interview.

## Policies

***Email.*** Course staff will make their best effort to reply to email within 48 weekday hours. However, due to high volume, staff cannot guarantee that all messages will receive replies.

***Accommodations.*** Reasonable accommodations will be made for any student with a qualifying disability. Such requests should be made through the Disabled Students Program (DSP). More information, instructions on how to access accommodations, and information on related resources can be found on the [DSP website](https://dsp.sa.ucsb.edu/). *Note: in this class there are no timed assessments.*

***Letter grades.*** Letter grades are assigned based only on the assessments identified above and according to [university guidelines](https://my.sa.ucsb.edu/catalog/Current/AcademicPoliciesProcedures/GradingSystem.aspx), with the relative weighting of assessments determined at the discretion of the instructor. While grade calculations will not be disclosed, students are entitled to an explanation of the criteria used to determine their grades if desired. Grades will not be changed except in the case of clerical errors. If students feel their grade has been unfairly assigned, they are entitled to contest it following [UCSB procedure for contesting grades](https://my.sa.ucsb.edu/catalog/Current/AcademicPoliciesProcedures/ContestedGrades.aspx).

***Conduct.*** All course participants are expected to maintain respectful and honorable conduct consistent with [UCSB ethical standards](https://www.compliance.ucsb.edu/ethics). Students uncomfortable with the behavior of another course participant for any reason should notify the instructor, course staff, or, if the complaint relates to course staff conduct, an administrative or departmental officer. Evidence of [academic dishonesty](https://studentconduct.sa.ucsb.edu/academic-integrity) will be reported to the Office of Student Conduct (OSC); evidence of problematic behavior will be addressed on a case-by-case basis in accord with university policies.
