---
title: "Sponsor a project"
editor: visual
---

## Why sponsor a project?

Our program is student-centered: data science capstone projects at UCSB are, above all, about creating educational and professional opportunities for students. We want to work with project sponsors who share this commitment and first and foremost wish to contribute to student learning. That said, projects also benefit sponsors by advancing pilot projects, generating new partnerships and collaborations, and providing a means of recruiting talent.

The most successful projects serve both ends by supporting students in making novel contributions to an ongoing research agenda. In our view, mutually beneficial success is most likely when sponsors:

-   are invested in students' intellectual and professional development and value their potential as future professionals, data science practitioners, and researchers;

-   have identified a well-defined problem of clear value to their agenda or organization and suitable for application of data science techniques, *and can articulate specific means/approaches for students to attempt to resolve the problem*;

-   can provide concrete starting points and prior work to students at the beginning of the project;

-   are willing to dedicate time and effort to training students on relevant background and to advising students as they progress.

## Logistics

We work with sponsors to develop a project plan during the Fall quarter (late September) each year. Once the project plan is confirmed, we assign students and a faculty or graduate student advisor to the project. Project work begins in Winter quarter (early January) and continues through the end of Spring quarter (early June), and culminates with a poster showcase on UCSB's campus.

Sponsors provide:

-   project objectives and datasets;

-   an advisor available to meet for one hour weekly or biweekly with the project team (virtual meetings ok) during the working period (January -- June);

-   (non-UCSB sponsors only) a participation fee to support the poster showcase and other program expenses.

UCSB provides:

-   advising on project plan development;

-   at least one faculty or graduate student co-advisor to join project meetings and assist students in meeting project goals;

-   student research team matched to the project based on interests and skills;

-   meeting space and research computing resources.

## How to sponsor a project

We are considering projects for the 2023-2024 academic year on a rolling basis through November 1, 2023. The process for proposing a project is as follows:

1.  Provide a short project pitch by filling out our interest form.
2.  If your project seems like a good fit for the program, the faculty coordinator for the capstone will contact you to request a project abstract. At this stage you can elect to meet with the coordinator for input on the project idea, if desired.
3.  The faculty coordinator will review your abstract and either accept the project, propose revisions, or decline the project.
4.  Project abstracts must be finalized by November 15, 2023 for distribution to students to solicit student preferences regarding team assignments.

For accepted projects, the general expectation is that datasets will be available to students no later than the first day of Winter quarter.

<!-- ### Disclosure agreements -->

<!-- Industry sponsors may wish to establish disclosure agreements covering the scope of project work. Typically such agreements pertain to data and information provided by the project sponsor for educational purposes, and are entered into by the university with the support of capstone program staff. Any such agreements are binding on students and faculty as university representatives. We are happy to establish these agreements provided they are not overly restrictive -- students will need to discuss their work with the class and prepare a public poster presentation in order to earn university credit. -->

<!-- It should be noted that the university cannot enter into agreements pertaining to ownership of project deliverables -- students retain rights to work that they produce for academic credit. -->
