---
title: "Schedule"
editor: visual
---

This schedule is tentative and may be adjusted at the discretion of the instructor.

+------+---------------+------------------------------------------------------------+--------------------------------------------------------+-------------------------------------+
| Week | Theme         | Tuesday meeting                                            | Thursday meeting                                       | Section meeting                     |
+======+===============+============================================================+========================================================+=====================================+
| 0    | Introductions | NO CLASS                                                   | Lecture: on research projects in(volving) data science | NO LAB                              |
+------+---------------+------------------------------------------------------------+--------------------------------------------------------+-------------------------------------+
| 1    | Introductions | Lecture: on data science as a discipline                   | 0.1 Discussion: class data                             | Software and technology overview    |
|      |               |                                                            |                                                        |                                     |
|      | Module 0      |                                                            |                                                        |                                     |
+------+---------------+------------------------------------------------------------+--------------------------------------------------------+-------------------------------------+
| 2    | Module 0      | 0.2 Lecture: on descriptive analysis                       | 0.3 Discussion: results                                | tidyverse basics                    |
+------+---------------+------------------------------------------------------------+--------------------------------------------------------+-------------------------------------+
| 3    | Module 1      | 1.1 Discussion                                             | 1.2 Lecture: on regression                             | lm()                                |
+------+---------------+------------------------------------------------------------+--------------------------------------------------------+-------------------------------------+
| 4    | Module 1      | 1.3 Lecture: on prediction                                 | 1.4 Discussion                                         | modelr and tidymodels               |
+------+---------------+------------------------------------------------------------+--------------------------------------------------------+-------------------------------------+
| 5    | Module 2      | 2.1 Discussion: biomarker data                             | 2.2 Lecture: on classification                         | glm()                               |
+------+---------------+------------------------------------------------------------+--------------------------------------------------------+-------------------------------------+
| 6    | Module 2      | 2.3 Lecture: on variable selection and variable importance | 2.4 Discussion: results                                | glmnet and randomForest             |
+------+---------------+------------------------------------------------------------+--------------------------------------------------------+-------------------------------------+
| 7    | Module 3      | 3.1 Discussion: soil temperature data                      | 3.2 Lecture: on time                                   | curve fitting; ts forecasting       |
+------+---------------+------------------------------------------------------------+--------------------------------------------------------+-------------------------------------+
| 8    | Module 3      | 3.3 Lecture: on space                                      | 3.4 Discussion: results                                | inverse distance weighting; kriging |
+------+---------------+------------------------------------------------------------+--------------------------------------------------------+-------------------------------------+
| 9    | Module 4      | 4.1                                                        | NO CLASS                                               | NO LAB                              |
+------+---------------+------------------------------------------------------------+--------------------------------------------------------+-------------------------------------+
| 10   | Module 4      | 4.2                                                        | 4.3 Discussion: in closing                             | Interviews                          |
+------+---------------+------------------------------------------------------------+--------------------------------------------------------+-------------------------------------+
