---
title: "Technology"
editor: visual
---

## Software

Computing in PSTAT197A will be shown in R, and codes and other materials will be shared via GitHub. The following software will be required to access course materials:

-   [R](https://www.r-project.org/) version 4.2.0+

-   [RStudio](https://www.rstudio.com/products/rstudio/download/) version 2022.07.1+

-   [Git](https://git-scm.com/downloads) version 2.36.1+

-   [GitHub Desktop](https://desktop.github.com/) (or another visual GitHub client)

Installations and basic functionality will be covered in the first section meeting.

While PSTAT197A is not language-agnostic and some instruction in R is provided, it is also not a course especially emphasizing programming technique in R. Students are free to use or experiment with other software at their discretion provided it does not interfere with their participation in the class, but are expected to submit work and collaborate using RStudio-supported files.

## GitHub

Students will learn and practice basic functionality of Git and GitHub for version control and collaboration by accessing course materials via GitHub repositories and submitting work via repository contributions.

We have a class [GitHub organization](https://github.com/pstat197) for the data science capstone. Enrolled students should request an email invitation from course staff if they have not received one.

Students have write access to all repositories within the organization and the ability to create their own public or private repositories. Course staff have administrator privileges.

Although the organization is invite-only, it is not private:

-   repositories for course modules are public, and anyone on the web can access them;

-   private repositories remain visible to course staff.

Students are asked to submit work by contributing to repositories for course modules. Any such contributions would remain publicly visible. Students can elect to keep their work on a private fork if they prefer.
